// 计数器模块
const COUNT_ADD = 'COUNT_ADD'
const COUNT_SUB = 'COUNT_SUB'

// TodoList模块
const TODO_ADD = 'TODO_ADD'
const TODO_SUB = 'TODO_SUB'

// 音乐模块
const SONG_ADD = 'SONG_ADD'
const SONG_DELETE_ALL = 'SONG_DELETE_ALL'
const SONG_GET_LIST = 'SONG_GET_LIST'
const SONG_GET_LIST_QQ = 'SONG_GET_LIST_QQ'

// 商品管理模块
const CART_ADD_GOOD = 'CART_ADD_GOOD'
const CART_DELETE_GOOD = 'CART_DELETE_GOOD'

export {
  COUNT_ADD,
  COUNT_SUB,
  TODO_ADD,
  TODO_SUB,
  SONG_ADD,
  SONG_DELETE_ALL,
  SONG_GET_LIST,
  SONG_GET_LIST_QQ,
  CART_ADD_GOOD,
  CART_DELETE_GOOD
}
